%% specular_reflection_overlap_spectrogram_grid
% -------------------------------------------------------------------------
% PURPOSE
%   Visualise how specular ground (water) reflection alters bat call spectra
%   as a function of bat height (h) and horizontal target distance (d).
%
%   The model explicitly accounts for the extra propagation path of a
%   specularly reflected echo relative to the direct path, and shows how
%   interference between the two copies produces distance- and height-
%   dependent spectral ripple patterns.
%
%   Output is a grid of spectrograms in which:
%     - rows correspond to bat height (h),
%     - columns correspond to target distance (d),
%     - each tile shows the overlapped (direct + reflected) call.
%
% -------------------------------------------------------------------------
% GEOMETRY / MODEL ASSUMPTIONS
%   - The bat emits a downward-directed call above a flat, specular surface
%     (e.g. calm water).
%   - The reflected path is modelled as a mirror image of the source across
%     the surface, yielding an effective vertical separation of 2h.
%   - Direct-path length:          L_dir = d
%   - Reflected-path length:       L_refl = sqrt(d^2 + (2h)^2)
%   - Path-length difference:      ΔL = L_refl − L_dir
%   - Time delay between copies:   Δt = ΔL / c
%
%   The indirect (reflected) call is generated by circularly shifting the
%   direct call by round(fs * Δt) samples.
%
% -------------------------------------------------------------------------
% SIGNAL MODEL
%   - Call: synthetic down-swept FM bat call generated by
%       generateVirtualBatCall(f_lo, f_hi, duration, fs, tailPadding)
%   - Overlap: arithmetic mean of the direct and delayed copies
%       overlap_call = 0.5 * (call + indirect_call)
%
%   This produces constructive and destructive interference in the
%   frequency domain (spectral ripples) whose spacing is governed by Δt.
%
% -------------------------------------------------------------------------
% PARAMETERS
%   distances : 1:10 m
%       Horizontal bat–target distances (columns of the grid).
%
%   heights   : 0.1:0.1:1 m
%       Bat heights above the reflecting surface (rows of the grid).
%
%   c         : 343 m/s
%       Speed of sound in air.
%
%   fs        : 192 kHz
%       Sampling rate for call synthesis and spectrogram computation.
%
% -------------------------------------------------------------------------
% VISUALISATION
%   - A single figure with a tiled layout (rows = heights, columns = distances).
%   - Each tile shows a spectrogram (img_spec) of the overlapped call.
%   - Axis labelling is minimised for clarity:
%       * Distance titles only on the top row.
%       * Height labels only on the first column.
%       * Frequency tick labels (kHz) only on the last column.
%       * Time tick labels (ms) only on the last row.
%
%   Spectrogram settings:
%       Window length : 128 samples
%       Overlap       : 127 samples
%       FFT length    : 4096
%       Dynamic range : 100 (linear divisor inside img_spec)
%
% -------------------------------------------------------------------------
% OUTPUT
%   - Figure titled:
%       'Overlapped Bat Calls: Heights vs Distances'
%   - Saved to:
%       ../fig/path_diff_model.(ext)
%     using saveFigure (helper function assumed to be on the MATLAB path).
%
% -------------------------------------------------------------------------
% DEPENDENCIES
%   - generateVirtualBatCall.m
%   - img_spec.m
%   - saveFigure.m
%
% -------------------------------------------------------------------------
% INTERPRETATION NOTES
%   - Increasing height (h) increases ΔL and hence Δt, producing denser
%     spectral ripples (smaller ripple spacing in frequency).
%   - Increasing distance (d) reduces the relative contribution of the
%     reflected path, flattening the interference pattern.
%   - This grid provides an intuitive visual map of how geometry alone
%     can structure spectral interference in bat echolocation over water.
% -------------------------------------------------------------------------
%% Specular reflection accounted model.
fig_path = '../fig';

% Parameters
distances = 1:10;              % in metres (columns)
heights = 0.1:0.1:1;           % in metres (rows)
c = 343;                       % speed of sound in m/s
fs = 192e3;                    % sample rate

% Generate reference bat call
call = generateVirtualBatCall(25e3, 90e3, 0.005, fs, 70);

% Create one figure for all subplots
f1 = figure;
sgtitle('Overlapped Bat Calls: Heights vs Distances')

% Setup tiled layout: rows = heights, cols = distances
tl = tiledlayout(length(heights), length(distances), ...
    'TileSpacing', 'compact', 'Padding', 'compact');

% Loop over each height (row)
for h = 1:length(heights)
    height = heights(h);

    for d = 1:length(distances)
        distance = distances(d);

        % Compute delay due to path difference
        dd = sqrt(distance^2 + (2*height)^2) - distance;
        dt = dd / c;
        f0 = 1 / (2*dt);

        % Generate overlapped call
        indirect_call = circshift(call, round(fs * dt));
        overlap_call = mean([call indirect_call], 2);

        % Plot in tile
        nexttile
        img_spec(overlap_call, 128, 127, 4096, fs, 100);
        axis square

        ax = gca;

        % Title: only on top row
        if h == 1
            title(sprintf('d = %dm', distance), 'FontSize', 14);
        else
            title('');
        end

        % Y-axis label: only on first column
        if d == 1
            ylabel(sprintf('h = %.1fm', height), 'FontSize', 14, 'FontWeight', 'bold');
            ax.YAxisLocation = 'left';
        else
            ax.YTickLabel = [];
        end

        % Y-axis tick labels: only on last column
        if d == length(distances)
            ax.YAxisLocation = 'right';
            ax.YTickLabel = ax.YTick ./ 1000;
            ylabel('kHz')
        else
            ax.YTickLabel = [];
        end

        % X-axis label: only on last row
        if h == length(heights)
            xlabel('ms', 'FontSize', 14);
            ax.XTickLabel = ax.XTick .* 1000;
        else
            ax.XTickLabel = [];
        end
    end
end
%% save figure
saveFigure(f1, fig_path, 'path_diff_model')